[package]
name = "asar-rust-bindings-proc-macros"
version = "0.1.1"
edition = "2021"
description = "Procedural macros for asar-rust-bindings"
license = "GPL-3.0"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.36"
syn = { version = "2.0.72", features = ["full"] }
