[package]
name = "asar-snes-proc-macros"
version = "0.1.4"
edition = "2021"
description = "Procedural macros for asar-snes"
license = "GPL-3.0"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.36"
syn = { version = "2.0.72", features = ["full"] }
